services:
  backend:
    build: ./backend
    ports:
      - "6969:6969"

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: rgsn
      POSTGRES_PASSWORD: rgsn
      POSTGRES_DB: rgsn-db
    volumes:
      - girlynetwork:/var/lib/postgresql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - backend

volumes:
  girlynetwork:
